export enum RequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PENDING_MANAGER_APPROVAL = 'PENDING_MANAGER_APPROVAL',
  APPROVED_PENDING_HCM = 'APPROVED_PENDING_HCM',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED_HCM_VALIDATION = 'FAILED_HCM_VALIDATION',
  FAILED_HCM_SUBMISSION = 'FAILED_HCM_SUBMISSION',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
}

export enum ActorType {
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  SYSTEM = 'SYSTEM',
}

export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  MANAGER = 'MANAGER',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  SYSTEM_INTEGRATION = 'SYSTEM_INTEGRATION',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum BalanceUnit {
  DAYS = 'DAYS',
}

export enum HcmSyncJobType {
  BATCH_IMPORT = 'BATCH_IMPORT',
  REALTIME_LOOKUP = 'REALTIME_LOOKUP',
  SUBMISSION = 'SUBMISSION',
  RECONCILIATION = 'RECONCILIATION',
}

export enum HcmSyncJobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum OutboxEventStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum ReconciliationIssueType {
  LOCAL_RESERVED_EXCEEDS_HCM_BALANCE = 'LOCAL_RESERVED_EXCEEDS_HCM_BALANCE',
  LOCAL_HCM_BALANCE_MISMATCH = 'LOCAL_HCM_BALANCE_MISMATCH',
  APPROVED_NOT_IN_HCM = 'APPROVED_NOT_IN_HCM',
  INVALID_DIMENSION = 'INVALID_DIMENSION',
  HCM_ACCEPTED_LOCAL_NOT_UPDATED = 'HCM_ACCEPTED_LOCAL_NOT_UPDATED',
}

export enum ReconciliationSeverity {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum HcmSubmissionStatus {
  ACCEPTED = 'ACCEPTED',
  DUPLICATE = 'DUPLICATE',
}
